// <auto-generated />
using HoaChat.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HoaChat.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HoaChat.Models.Anh", b =>
                {
                    b.Property<int>("idAnh")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idAnh"));

                    b.Property<int>("idHoaChat")
                        .HasColumnType("int");

                    b.Property<string>("tenAnh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idAnh");

                    b.HasIndex("idHoaChat");

                    b.ToTable("Anh");
                });

            modelBuilder.Entity("HoaChat.Models.HoaChat", b =>
                {
                    b.Property<int>("idHoaChat")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idHoaChat"));

                    b.Property<int>("iDLoaiHC")
                        .HasColumnType("int");

                    b.Property<string>("khaiNiem")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("moTa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("mucDich")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phuongPhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phuongTien")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("tenHoaChat")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trangThai")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("trieuChung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("xamNhap")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idHoaChat");

                    b.HasIndex("iDLoaiHC");

                    b.ToTable("HoaChat");
                });

            modelBuilder.Entity("HoaChat.Models.LoaiHoaChat", b =>
                {
                    b.Property<int>("iDLoaiHC")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("iDLoaiHC"));

                    b.Property<string>("loaiHC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("iDLoaiHC");

                    b.ToTable("LoaiHoaChat");
                });

            modelBuilder.Entity("HoaChat.Models.Video", b =>
                {
                    b.Property<int>("idVideo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("idVideo"));

                    b.Property<int>("idHoaChat")
                        .HasColumnType("int");

                    b.Property<string>("tieuDe")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("video")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("idVideo");

                    b.HasIndex("idHoaChat");

                    b.ToTable("Video");
                });

            modelBuilder.Entity("HoaChat.Models.Anh", b =>
                {
                    b.HasOne("HoaChat.Models.HoaChat", "HoaChat")
                        .WithMany("Anhs")
                        .HasForeignKey("idHoaChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaChat");
                });

            modelBuilder.Entity("HoaChat.Models.HoaChat", b =>
                {
                    b.HasOne("HoaChat.Models.LoaiHoaChat", "LoaiHoaChat")
                        .WithMany("HoaChats")
                        .HasForeignKey("iDLoaiHC")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiHoaChat");
                });

            modelBuilder.Entity("HoaChat.Models.Video", b =>
                {
                    b.HasOne("HoaChat.Models.HoaChat", "HoaChat")
                        .WithMany("Videos")
                        .HasForeignKey("idHoaChat")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoaChat");
                });

            modelBuilder.Entity("HoaChat.Models.HoaChat", b =>
                {
                    b.Navigation("Anhs");

                    b.Navigation("Videos");
                });

            modelBuilder.Entity("HoaChat.Models.LoaiHoaChat", b =>
                {
                    b.Navigation("HoaChats");
                });
#pragma warning restore 612, 618
        }
    }
}
